{% set name = "mbuild" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/mbuild/archive/{{ version }}.tar.gz
  sha256: 9f75a4c5efda5a27619ad373d46600715e774c16aed14660d2a4a874ec6a98c1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - protobuf
    - python >=3.6
  run:
    - mdtraj
    - numpy
    - oset
    - scipy
    - packmol
    - parmed
    - protobuf
    - python >=3.6

test:
  imports:
    - mbuild

about:
  home: https://github.com/mosdef-hub/mbuild
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A hierarchical, component based molecule builder.

  # The remaining entries in this section are optional, but recommended.
  description: |
    With just a few lines of mBuild code, you can assemble reusable components into
    complex molecular systems for molecular dynamics simulations. mBuild is
    designed to minimize or even eliminate the need to explicitly translate and
    orient components when building systems: you simply tell it to connect two
    pieces! mBuild also keeps track of the system's topology so you don't have to
    worry about manually defining bonds when constructing chemically bonded
    structures from smaller components.
  doc_url: https://mbuild.mosdef.org/
  dev_url: https://github.com/mosdef-hub/mbuild

extra:
  recipe-maintainers:
    - bdice
    - justinGilmer
    - rmatsum836
    - daico007
    - umesh-timalsina
