{% set name = "mbuild" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/mbuild/archive/{{ version }}.tar.gz
  sha256: b338aeec22b306a67003378b2fbfa4358cdb69100cefe8202fd91fdfefc74fb7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - protobuf
    - python >=3.8, <=3.11
  run:
    - mdtraj
    - networkx
    - treelib
    - numpy
    - scipy
    - packmol
    - parmed >=3.4.0
    - ele
    - protobuf
    - rdkit >=2021
    - python >=3.8, <=3.11
    - boltons
    - importlib_resources
  run_constrained:
    - foyer >=0.11.0

test:
  imports:
    - mbuild

about:
  home: https://github.com/mosdef-hub/mbuild
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A hierarchical, component based molecule builder.

  # The remaining entries in this section are optional, but recommended.
  description: |
    With just a few lines of mBuild code, you can assemble reusable components into
    complex molecular systems for molecular dynamics simulations. mBuild is
    designed to minimize or even eliminate the need to explicitly translate and
    orient components when building systems: you simply tell it to connect two
    pieces! mBuild also keeps track of the system's topology so you don't have to
    worry about manually defining bonds when constructing chemically bonded
    structures from smaller components.
  doc_url: https://mbuild.mosdef.org/
  dev_url: https://github.com/mosdef-hub/mbuild

extra:
  recipe-maintainers:
    - bdice
    - justinGilmer
    - rmatsum836
    - daico007
    - umesh-timalsina
