{% set name = "mbuild" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/mbuild/archive/{{ version }}.tar.gz
  sha256: f13d9982391217494690930501447893114a2cb7815c186bced193192cd8dd7a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - mdtraj
    - networkx
    - treelib
    - numpy >=2.0
    - scipy
    - packmol >=20.15
    - parmed >=3.4.0
    - ele
    - gmso >=0.12.0
    - rdkit >=2021
    - python >={{ python_min }},<3.13a0
    - boltons
  run_constrained:
    - foyer >=0.11.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - mbuild

about:
  home: https://github.com/mosdef-hub/mbuild
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A hierarchical, component based molecule builder.

  # The remaining entries in this section are optional, but recommended.
  description: |
    With just a few lines of mBuild code, you can assemble reusable components into
    complex molecular systems for molecular dynamics simulations. mBuild is
    designed to minimize or even eliminate the need to explicitly translate and
    orient components when building systems: you simply tell it to connect two
    pieces! mBuild also keeps track of the system's topology so you don't have to
    worry about manually defining bonds when constructing chemically bonded
    structures from smaller components.
  doc_url: https://mbuild.mosdef.org/
  dev_url: https://github.com/mosdef-hub/mbuild

extra:
  recipe-maintainers:
    - chrisjonesBSU
    - bdice
    - justinGilmer
    - rmatsum836
    - daico007
    - umesh-timalsina
    - CalCraven
